#server:
#  port: 8080
#spring:
#  application:
#    name: admin-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/admin_db
#    username: postgres
#    password: Informatique94
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 30  # Heartbeat interval (default)
#    leaseExpirationDurationInSeconds: 90  # Time before Eureka considers the instance expired (default)
#jwt:
#  secret: X7K9p2mQ8vL5rT3yZn6bQeF4uA1wJ9kLmN5oP6sR7tU8vW9xY0z1aB2c3d4E5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D  # Use this 64-byte base64 key


server:
  port: 8080
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://postgres-admin:5432/admin_db  # Update to use service name in Kubernetes
    username: postgres
    password: Informatique94
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://10.200.1.203:8761/eureka/  # Replace eureka-server with IP
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # Optional: ensures IP registration
    leaseRenewalIntervalInSeconds: 30  # Heartbeat interval (default)
    leaseExpirationDurationInSeconds: 90  # Time before Eureka considers the instance expired (default)
jwt:
  secret: X7K9p2mQ8vL5rT3yZn6bQeF4uA1wJ9kLmN5oP6sR7tU8vW9xY0z1aB2c3d4E5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D